# Generated by Django 3.2.16 on 2023-02-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(upload_to=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tags',
            field=models.CharField(max_length=255),
        ),
    ]
