# Generated by Django 3.2.16 on 2023-02-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_post_postimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postimg',
            new_name='imgup',
        ),
    ]
