# Generated by Django 3.2.16 on 2023-02-17 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20230216_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
