# Generated by Django 3.2.16 on 2023-02-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_catagory_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='post_date',
        ),
    ]
