# Generated by Django 3.2.16 on 2023-02-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
