# Generated by Django 3.2.16 on 2023-02-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_auto_20230221_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
