# Generated by Django 3.2.16 on 2023-02-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0031_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
